# Generated by Django 4.2.8 on 2025-11-30 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model_share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraoDoiNoiBo',
            fields=[
                ('MaTin', models.AutoField(primary_key=True, serialize=False)),
                ('TieuDe', models.CharField(max_length=255)),
                ('NoiDung', models.TextField()),
                ('FileDinhKem', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ThoiGianGui', models.DateTimeField(auto_now_add=True)),
                ('TrangThai', models.CharField(choices=[('Đã gửi', 'Đã gửi'), ('Nháp', 'Nháp'), ('Đã xóa', 'Đã xóa')], default='Nháp', max_length=100)),
                ('DaXoa', models.BooleanField(default=False)),
                ('LaTinNhap', models.BooleanField(default=False)),
                ('DonViTrucThuoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model_share.phongban')),
                ('NguoiGui', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tin_da_gui', to=settings.AUTH_USER_MODEL)),
                ('NguoiNhan', models.ManyToManyField(blank=True, related_name='tin_den', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
