# Generated by Django 4.2.8 on 2025-11-30 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CongViec',
            fields=[
                ('MaCV', models.AutoField(primary_key=True, serialize=False)),
                ('TieuDe', models.CharField(max_length=255)),
                ('MoTa', models.CharField(blank=True, max_length=255, null=True)),
                ('NgayNhan', models.DateField()),
                ('HanXuLy', models.DateField()),
                ('TrangThai', models.CharField(choices=[('Chờ xử lý', 'Chờ xử lý'), ('Đang xử lý', 'Đang xử lý'), ('Yêu cầu sửa', 'Yêu cầu sửa'), ('Chờ phê duyệt', 'Chờ phê duyệt'), ('Hoàn thành', 'Hoàn thành')], default='Chờ xử lý', max_length=100)),
                ('FileDinhKem', models.FileField(blank=True, null=True, upload_to='cong_viec/')),
                ('NgayHoanThanh', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NguoiXuLy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VaiTro', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('duyet_van_ban', 'Duyệt văn bản đi'), ('phan_hoi_van_ban', 'Phản hồi văn bản đi'), ('van_ban_den', 'Văn bản đến'), ('cong_viec', 'Công việc'), ('trao_doi', 'Trao đổi nội bộ')], default='cong_viec', max_length=50)),
                ('related_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('MaPB', models.AutoField(primary_key=True, serialize=False)),
                ('TenPB', models.CharField(default='Chưa xác định', max_length=255)),
                ('MoTa', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anh_dai_dien', models.ImageField(blank=True, upload_to='anh_dai_dien/')),
                ('vai_tro', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VanBanDen',
            fields=[
                ('MaVanBanDen', models.AutoField(primary_key=True, serialize=False)),
                ('SoDen', models.IntegerField()),
                ('NgayDen', models.DateField()),
                ('SoKyHieu', models.CharField(max_length=255, unique=True)),
                ('TrichYeu', models.CharField(max_length=255)),
                ('CoQuanBanHanh', models.CharField(max_length=100)),
                ('NguoiXuLyChinh', models.CharField(blank=True, max_length=255, null=True)),
                ('NguoiXuLy', models.CharField(blank=True, max_length=255, null=True)),
                ('HanXuLy', models.DateField(blank=True, null=True)),
                ('LoaiVanBan', models.CharField(max_length=100)),
                ('TrangThai', models.CharField(choices=[('Đang xử lý', 'Đang xử lý'), ('Chờ phê duyệt', 'Chờ phê duyệt'), ('Chờ xử lý', 'Chờ xử lý')], default='Chờ xử lý', max_length=100)),
                ('DoKhan', models.CharField(choices=[('Thường', 'Thường'), ('Khẩn', 'Khẩn')], default='Thường', max_length=50)),
                ('DoMat', models.CharField(choices=[('Thường', 'Thường'), ('Mật', 'Mật')], default='Thường', max_length=50)),
                ('NguoiKy', models.CharField(max_length=255)),
                ('NguoiDuyet', models.CharField(max_length=255)),
                ('NgayBanHanh', models.DateField(blank=True, null=True)),
                ('FileDinhKem', models.FileField(blank=True, null=True, upload_to='vanbanden/')),
                ('NguoiNhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vanbanden_nhan', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YeuCauSua',
            fields=[
                ('MaYeuCau', models.AutoField(primary_key=True, serialize=False)),
                ('TieuDe', models.CharField(max_length=255)),
                ('NoiDung', models.TextField()),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('FileDinhKem', models.FileField(blank=True, null=True, upload_to='yeu_cau_sua/')),
                ('CongViecLienQuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_share.congviec')),
                ('NguoiYeuCau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeu_cau_gui', to=settings.AUTH_USER_MODEL)),
                ('VanBanLienQuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_share.vanbanden')),
            ],
        ),
    ]
