# Generated by Django 4.2.8 on 2025-11-30 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model_share', '0001_initial'),
        ('vanbandi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbanden',
            name='van_ban_di_lien_quan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vanbandi.vanbandi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phong_ban',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model_share.phongban'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nguoixuly',
            name='CongViec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_phoi_hop', to='model_share.congviec'),
        ),
        migrations.AddField(
            model_name='nguoixuly',
            name='NguoiDung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='congviec',
            name='MaVanBanDen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_share.vanbanden'),
        ),
        migrations.AddField(
            model_name='congviec',
            name='NguoiXuLyChinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
