# Generated by Django 4.2.8 on 2025-11-30 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model_share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VanBanDi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trich_yeu', models.TextField(blank=True, null=True)),
                ('han_xu_ly', models.DateField(blank=True, null=True)),
                ('so_van_ban', models.CharField(max_length=50, unique=True)),
                ('co_quan_ban_hanh', models.CharField(blank=True, max_length=255, null=True)),
                ('ngay_tao', models.DateField(auto_now_add=True)),
                ('loai_van_ban', models.CharField(blank=True, max_length=255, null=True)),
                ('trang_thai', models.CharField(choices=[('Mới', 'Mới (Draft)'), ('Chờ duyệt', 'Chờ Cấp trên duyệt'), ('Đã ban hành', 'Đã Ban hành'), ('Bị từ chối', 'Bị Từ chối/Yêu cầu sửa')], default='Mới', max_length=50)),
                ('file_du_thao', models.FileField(blank=True, null=True, upload_to='du_thao/')),
                ('file_lien_quan', models.FileField(blank=True, null=True, upload_to='lien_quan/')),
                ('nguoi_duyet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_outgoing_documents', to=settings.AUTH_USER_MODEL)),
                ('nguoi_lap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafted_documents', to=settings.AUTH_USER_MODEL)),
                ('nguoi_nhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_outgoing_documents', to=settings.AUTH_USER_MODEL)),
                ('van_ban_den_lien_quan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model_share.vanbanden')),
            ],
        ),
    ]
